# @ is used to suppress outputting the command itself


default : xaa
	@echo "hello from default"
xaa : xab 
	@echo "hello from xaa"
	
xab : xac 
	@echo "hello from xab"
	# XD
	
	@# XD
xac : 
	@echo "hello from xac"
